GET http://localhost:8080/api/courier
Accept: application/json

###

POST http://localhost:8080/api/courier
Content-Type: application/json

{
  "createdById": 1,
  "modifiedById": 1,
  "createdDate": "2021-05-16T04:25:03Z",
  "modifiedDate": "2021-06-16T04:25:03Z",
  "firstName": "Rest",
  "lastName": "Teszt",
  "phoneNumber": "+3645999999"
}

###

PUT http://localhost:8080/api/courier
Content-Type: application/json

{
  "id": 7,
  "createdById": 1,
  "modifiedById": 1,
  "createdDate": "2021-05-16T04:25:03Z",
  "modifiedDate": "2021-06-16T04:25:03Z",
  "firstName": "Légyszi",
  "lastName": "Légyszi",
  "phoneNumber": "+3645222222"
}

###

DELETE http://localhost:8080/api/courier/7
Accept: application/json

###