GET http://localhost:8080/api/order
Accept: application/json

###

GET http://localhost:8080/api/order/23
Accept: application/json

###

POST http://localhost:8080/api/order
Content-Type: application/json

{
  "createdById": 1,
  "modifiedById": 1,
  "createdDate": "2020-11-16T04:25:03Z",
  "modifiedDate": "2020-11-16T04:25:03Z",
  "deliveredDate": "2021-09-30T12:21:00Z[UTC]",
  "houseNumber": "22323",
  "natureOfPublicSpace": "REST TESZT",
  "furnitures": [
    1,
    2
  ],
  "publicSpace": "REST TESZT",
  "settlement": "REST TESZT"
}

###

PUT http://localhost:8080/api/order
Content-Type: application/json

{
  "id": 28,
  "createdById": 1,
  "modifiedById": 1,
  "createdDate": "2010-11-16T04:25:03Z",
  "modifiedDate": "2020-11-16T04:25:03Z",
  "deliveredDate": "2021-09-30T12:21:00Z[UTC]",
  "houseNumber": "REST TESZTELÉS",
  "natureOfPublicSpace": "REST TESZTELÉS",
  "furnitures": [
    1,
    2,
    3
  ],
  "publicSpace": "REST TESZTELÉS",
  "settlement": "REST TESZTELÉS"
}

###

DELETE http://localhost:8080/api/order/26
Accept: application/json

###